### ISSUE TITLE
Windows 11 Navigation Pane Context Menu causing File Explorer crashes

### ISSUE THREAD

**Issue by Spiretail** [winseros/pboman3#27]
### Issue
When using W11, right clicking on a drive or folder in the navigation pane of File Explorer, and attempting to do any context menu action will crash File Explorer, and restart it.

### Steps to re-produce
1. Open File Explorer
2. Right click any item in the left hand navigation pane
3. Hit "Properties" or any other context menu action
4. File Explorer restarts

Installer version of V1.4.0, yet to test on binaries version.

**Comment by lilkingjr1** [comment]
Wow, so I'm not crazy and this isn't just me 🤣

@winseros Thank you so so much for being active and looking into this issue!

I'd like to bump this issue with my situation as well:
- **PBO Man. Ver.**: 1.2.0 (Installer)
  - I'm about to try 1.4.0 (Installer), but I doubt it will resolve this issue.
- **Windows Ver.**: Windows 10 Pro 21H2
- **Affected Autoruns Entry**: `HKLM\Software\Classes\Folder\ShellEx\ContextMenuHandlers\pboman3`
- **Affected Image Path**: `D:\Program Files\PBO Manager\pboe.dll`

Disabling this entry in [Autoruns](https://docs.microsoft.com/en-us/sysinternals/downloads/autoruns) seems to resolve the issue, but this also obviously removes the shell extension from the right-click menu which is not desired. I first thought my issue was exactly the same as Spiretail's, but it's actually not required to do any action for it to crash. All you have to do is right-click any specific entry in the context menu and wait about 3-5 sec. for explorer.exe to crash and reboot. As for the specific entries, it seems to be any item under the "This PC" section of the context menu.

If it's possible to disable the shell extension entry for any items under the "This PC" section, I think that would be a quick and easy fix since users likely won't want to PBO package their entire Documents folder, or any folder in that list really. If that's not possible, I unfortunately don't have a resolution suggustion since I'm not well versed yet on writing shell extensions.

**Comment by winseros** [comment]
Guys, could you check the binaries from the [build #99](https://github.com/winseros/pboman3/actions/runs/2558071017) and let me know? If they work fine, I'll promote them to a release.

**Comment by lilkingjr1** [comment]
> Guys, could you check the binaries from the [build #99](https://github.com/winseros/pboman3/actions/runs/2558071017) and let me know? If they work fine, I'll promote them to a release.

Seems to have fixed it for me! Thanks! :)

**Comment by winseros** [comment]
Published the artifacts as [Release v1.4.1](https://github.com/winseros/pboman3/releases/tag/v1.4.1)
